sudo: required

language: ruby

cache:
  directories:
  - docker
  - vendor/bundle

services:
  - docker

before_install:
  - gem install -f docker-api
  - mkdir -p /tmp/dind
  - docker run --privileged -v /tmp/dind:/var/run -d fgrehm/alpine-dind
  - export DOCKER_HOST='unix:///tmp/dind/docker.sock'
  - export DOCKER_TLS_VERIFY=0

script:
  - docker pull chinthakagodawita/soe:php5.5
  - docker run -d --name=soe -t chinthakagodawita/soe:php5.5
  - docker exec soe "supervisorctl status"
  - docker kill soe
  - docker rm soe
  # - ruby _scripts/travis-docker-test.rb
  # - bundle exec rake docker:build
  # - bundle exec rspec spec/soe/php55_spec.rb

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ]); then bundle exec rake docker:publish; fi
